import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { DesktopLayout } from "@/components/layouts/DesktopLayout";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <DesktopLayout>{children}</DesktopLayout>
      </body>
    </html>
  );
}
